name: build-postgis-mysql
run-name: Build Python 3.13 + Postgis + MySQL

on:
  pull_request:
    paths:
      - .github/workflows/build-python-postgis-mysql.yml
      - python-postgis-mysql.Dockerfile
      - scripts/cleanup.sh
      - scripts/install-common.sh
      - scripts/install-mysql.sh
      - scripts/install-postgres-client.sh
      - scripts/prep-postgis-mysql.sh

concurrency:
  group: build-postgis-mysql-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6.15.0
        with:
          file: python-postgis-mysql.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: uninen/python-postgis-mysql:3.13
